import fs from 'node:fs';
import path from 'node:path';
import type { Task } from '../types.js';
import { parseSteps, parseVerifyMode } from '../types.js';

/** Resolve the plan content to inline into LOOP_TASK.md (best effort). */
function planContent(task: Task): string {
  const ref = task.plan_ref?.trim();
  if (!ref) return '(no plan attached)';
  if (/^https?:\/\//i.test(ref)) return `See plan at: ${ref}`;
  try {
    return fs.readFileSync(ref, 'utf8');
  } catch {
    return `(could not read plan file: ${ref})`;
  }
}

/**
 * Write LOOP_TASK.md into the worktree. The dispatch prompt only tells the agent to
 * read this file, so all task context lives here (goal, plan, verification, rules).
 * `extras.knowledge` (when non-null) is inserted as a `## Knowledge / Environment`
 * section between Goal and Plan; omitted entirely when null/absent, so an empty
 * knowledge base produces byte-identical output to before this option existed.
 */
export function writeTaskFile(cwd: string, task: Task, extras?: { knowledge?: string | null }): string {
  const steps = parseSteps(task);
  const modes = parseVerifyMode(task);
  const file = path.join(cwd, 'LOOP_TASK.md');
  const knowledgeBlock = extras?.knowledge
    ? `\n## Knowledge / Environment\n（以下為使用者的長期環境／偏好／限制知識，執行本任務時必須遵守；若與 Plan 衝突，以 Plan 為準）\n${extras.knowledge}\n`
    : '';
  const acceptanceBlock = task.verify_rubric?.trim()
    ? `\n## 驗收標準 (Acceptance)\n${task.verify_rubric.trim()}\n`
    : '';
  const manualRule = modes.has('manual')
    ? '\n- 你可能無法在此環境完整驗證（缺硬體/非目標 OS）。盡量自動驗證能驗的部分，並在 repo 根目錄寫一份 `VERIFY.md`：列出你做了什麼、還有哪些必須在目標環境（硬體/公司 Windows）手動驗證的具體步驟與預期結果。'
    : '';
  const body = `# Loop task: ${task.title}

## Goal
${task.goal}
${knowledgeBlock}
## Plan
${planContent(task)}

## Verification steps (must all pass before you finish)
${steps.map((s) => `- \`${s}\``).join('\n') || '- (none)'}
${acceptanceBlock}
## Rules
- Only modify files needed for this task; do not touch anything outside its scope.
- Commit your work in small, conventional commits.
- Maintain a \`HANDOFF.md\` at the repo root with sections: Done / TODO / Key decisions / How to resume. Update AND commit it before any long or risky step, so a resumed run can pick up exactly where you left off if you are interrupted near the usage limit.
- If a \`LOOP_RESUME_CONTEXT.md\` is present, a previous attempt was interrupted or its verification failed — read it FIRST and continue from there instead of starting over.
- Before finishing, run the verification steps yourself and fix until they pass.
- If you cannot complete the task, clearly explain the blocker and stop — do not force a workaround.${manualRule}
`;
  fs.writeFileSync(file, body);
  return file;
}

/**
 * Persist the failing verification step + captured output tail as LOOP_RESUME_CONTEXT.md
 * in the worktree, so a resumed run inherits the failure context and fixes it in place
 * rather than re-deriving what broke. Returns the file path.
 */
export function writeResumeContext(cwd: string, failedStep: string, outputTail: string): string {
  const file = path.join(cwd, 'LOOP_RESUME_CONTEXT.md');
  const body = `# Resume context (auto-generated by Loop Engineering)

The previous attempt finished its coding phase but a **verification step FAILED**.
You have been resumed in the same session and worktree to FIX it — do not start over.
Inspect the failure below, fix the root cause, then re-run ALL verification steps until
they pass.

## Failed step
\`${failedStep}\`

## Captured output (tail)
\`\`\`
${outputTail.trim() || '(no output captured)'}
\`\`\`
`;
  fs.writeFileSync(file, body);
  return file;
}

/**
 * Gather the state a resumed run should be primed with: the verify-failure context and
 * the agent-maintained HANDOFF.md (either may be absent). Returned as a bounded excerpt
 * to inline into the resume prompt; null when there is nothing to hand off.
 */
export function collectResumeContext(cwd: string): string | null {
  const parts: string[] = [];
  for (const name of ['LOOP_RESUME_CONTEXT.md', 'HANDOFF.md']) {
    try {
      const txt = fs.readFileSync(path.join(cwd, name), 'utf8').trim();
      if (txt) parts.push(`## ${name}\n${txt}`);
    } catch {
      /* absent — fine */
    }
  }
  if (parts.length === 0) return null;
  return parts.join('\n\n').slice(0, 4000);
}
