import fs from 'node:fs';
import path from 'node:path';
import type Database from 'better-sqlite3';
import type { KnowledgeNode } from './types.js';
import { repoScope } from './types.js';
import { mdInline } from './context.js';

const START_MARKER =
  '<!-- loop-knowledge:start (auto-generated by Loop Engineering — edit via the 知識庫 page, not here) -->';
const END_MARKER = '<!-- loop-knowledge:end -->';
const HEADING = '## 環境與約束（Loop 知識庫）';

// Mainstream guidance is a tiny always-on context: only the kinds an outside tool
// (Cursor/Copilot on the company machine) needs to behave correctly, not the whole KB.
const EXPORT_KINDS = new Set(['environment', 'constraint', 'preference']);

export interface ExportClaudeMdResult {
  ok: boolean;
  error?: string;
  path?: string;
  nodeCount?: number;
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function renderBlock(nodes: KnowledgeNode[]): string {
  const lines = nodes.map((n) => `- **[${n.kind}] ${mdInline(n.title)}**：${mdInline(n.body)}`);
  return [START_MARKER, HEADING, ...lines, END_MARKER].join('\n');
}

/**
 * Collects approved+active nodes relevant to `repoPath` (scope global + repo:<realpath>,
 * plus one active edge hop out from that seed set — same tier logic as knowledgeContext),
 * restricted to environment/constraint/preference kinds, and renders them into a
 * marker-fenced block in the target repo's CLAUDE.md. Idempotent: replaces the existing
 * fenced block in place (or appends/creates it) and never touches content outside the
 * markers. Returns an error result (never throws) when repoPath isn't a directory.
 */
export function exportClaudeMd(db: Database.Database, repoPath: string): ExportClaudeMdResult {
  let stat: fs.Stats;
  try {
    stat = fs.statSync(repoPath);
  } catch {
    return { ok: false, error: `repo path does not exist: ${repoPath}` };
  }
  if (!stat.isDirectory()) {
    return { ok: false, error: `repo path is not a directory: ${repoPath}` };
  }

  const seedScopes = ['global', repoScope(repoPath)];
  const seedPlaceholders = seedScopes.map(() => '?').join(', ');
  const tier0 = db
    .prepare(
      `SELECT * FROM knowledge_nodes
        WHERE status = 'approved' AND invalid_at IS NULL AND scope IN (${seedPlaceholders})`,
    )
    .all(...seedScopes) as KnowledgeNode[];

  const tier0Ids = new Set(tier0.map((n) => n.id));
  let tier1: KnowledgeNode[] = [];
  if (tier0.length) {
    const idPlaceholders = tier0.map(() => '?').join(', ');
    const edgeRows = db
      .prepare(
        `SELECT src, dst FROM knowledge_edges
          WHERE invalid_at IS NULL AND (src IN (${idPlaceholders}) OR dst IN (${idPlaceholders}))`,
      )
      .all(...tier0.map((n) => n.id), ...tier0.map((n) => n.id)) as { src: string; dst: string }[];

    const neighborIds = new Set<string>();
    for (const e of edgeRows) {
      if (tier0Ids.has(e.src) && !tier0Ids.has(e.dst)) neighborIds.add(e.dst);
      if (tier0Ids.has(e.dst) && !tier0Ids.has(e.src)) neighborIds.add(e.src);
    }
    if (neighborIds.size) {
      const nIds = [...neighborIds];
      const nPlaceholders = nIds.map(() => '?').join(', ');
      tier1 = db
        .prepare(
          `SELECT * FROM knowledge_nodes
            WHERE status = 'approved' AND invalid_at IS NULL AND id IN (${nPlaceholders})`,
        )
        .all(...nIds) as KnowledgeNode[];
    }
  }

  const byId = new Map<string, KnowledgeNode>();
  for (const n of [...tier0, ...tier1]) {
    if (EXPORT_KINDS.has(n.kind)) byId.set(n.id, n);
  }
  const nodes = [...byId.values()].sort(
    (a, b) => b.weight - a.weight || a.title.localeCompare(b.title),
  );

  const block = renderBlock(nodes);
  const claudeMdPath = path.join(repoPath, 'CLAUDE.md');
  let existing = '';
  try {
    existing = fs.readFileSync(claudeMdPath, 'utf8');
  } catch {
    existing = '';
  }

  const markerRe = new RegExp(`${escapeRegExp(START_MARKER)}[\\s\\S]*?${escapeRegExp(END_MARKER)}`);
  let next: string;
  if (markerRe.test(existing)) {
    next = existing.replace(markerRe, block);
  } else if (existing.length) {
    next = existing.replace(/\n*$/, '') + '\n\n' + block + '\n';
  } else {
    next = block + '\n';
  }

  fs.writeFileSync(claudeMdPath, next, 'utf8');
  return { ok: true, path: claudeMdPath, nodeCount: nodes.length };
}
